[2024-09-10T17:24:57.695+0000] {processor.py:186} INFO - Started process (PID=52) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:24:57.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:24:57.697+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:24:57.697+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:24:57.702+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:24:57.701+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:24:57.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:24:57.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.024 seconds
[2024-09-10T17:25:28.465+0000] {processor.py:186} INFO - Started process (PID=115) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:25:28.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:25:28.467+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:25:28.467+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:25:28.472+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:25:28.471+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:25:28.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:25:28.483+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.023 seconds
[2024-09-10T17:25:58.612+0000] {processor.py:186} INFO - Started process (PID=178) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:25:58.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:25:58.614+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:25:58.614+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:25:58.620+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:25:58.619+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:25:58.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:25:58.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.023 seconds
[2024-09-10T17:26:29.016+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:26:29.017+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:26:29.019+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:26:29.018+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:26:29.024+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:26:29.023+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:26:29.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:26:29.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.025 seconds
[2024-09-10T17:26:59.258+0000] {processor.py:186} INFO - Started process (PID=304) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:26:59.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:26:59.260+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:26:59.259+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:26:59.265+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:26:59.264+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:26:59.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:26:59.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.028 seconds
[2024-09-10T17:27:29.520+0000] {processor.py:186} INFO - Started process (PID=367) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:27:29.520+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:27:29.522+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:27:29.522+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:27:29.528+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:27:29.527+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:27:29.529+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:27:29.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.024 seconds
[2024-09-10T17:27:59.848+0000] {processor.py:186} INFO - Started process (PID=430) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:27:59.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:27:59.849+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:27:59.849+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:27:59.854+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:27:59.853+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:27:59.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:27:59.869+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.024 seconds
[2024-09-10T17:28:30.156+0000] {processor.py:186} INFO - Started process (PID=493) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:28:30.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:28:30.158+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:28:30.158+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:28:30.164+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:28:30.163+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:28:30.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:28:30.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.026 seconds
[2024-09-10T17:29:00.466+0000] {processor.py:186} INFO - Started process (PID=556) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:29:00.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:29:00.468+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:29:00.467+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:29:00.473+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:29:00.472+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:29:00.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:29:00.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.025 seconds
[2024-09-10T17:29:30.896+0000] {processor.py:186} INFO - Started process (PID=619) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:29:30.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:29:30.898+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:29:30.897+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:29:30.903+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:29:30.902+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:29:30.904+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:29:30.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.027 seconds
[2024-09-10T17:30:01.458+0000] {processor.py:186} INFO - Started process (PID=688) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:30:01.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:30:01.460+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:30:01.460+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:30:01.466+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:30:01.464+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:30:01.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:30:01.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.021 seconds
[2024-09-10T17:30:31.782+0000] {processor.py:186} INFO - Started process (PID=751) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:30:31.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:30:31.784+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:30:31.784+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:30:31.796+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:30:31.794+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:30:31.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:30:31.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.045 seconds
[2024-09-10T17:31:01.984+0000] {processor.py:186} INFO - Started process (PID=814) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:31:01.985+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:31:01.986+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:31:01.986+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:31:01.992+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:31:01.991+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:31:01.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:31:02.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.023 seconds
[2024-09-10T17:31:32.497+0000] {processor.py:186} INFO - Started process (PID=877) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:31:32.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:31:32.499+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:31:32.499+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:31:32.504+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:31:32.503+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:31:32.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:31:32.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.026 seconds
[2024-09-10T17:32:02.976+0000] {processor.py:186} INFO - Started process (PID=940) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:32:02.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:32:02.979+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:32:02.979+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:32:02.987+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:32:02.985+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:32:02.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:32:02.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.027 seconds
[2024-09-10T17:32:33.356+0000] {processor.py:186} INFO - Started process (PID=1003) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:32:33.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:32:33.359+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:32:33.358+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:32:33.364+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:32:33.363+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:32:33.365+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:32:33.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.023 seconds
[2024-09-10T17:33:03.567+0000] {processor.py:186} INFO - Started process (PID=1066) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:33:03.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:33:03.569+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:33:03.569+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:33:03.574+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:33:03.573+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:33:03.575+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:33:03.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.025 seconds
[2024-09-10T17:33:33.719+0000] {processor.py:186} INFO - Started process (PID=1129) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:33:33.720+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:33:33.721+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:33:33.721+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:33:33.726+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:33:33.725+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:33:33.727+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:33:33.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.023 seconds
[2024-09-10T17:34:03.947+0000] {processor.py:186} INFO - Started process (PID=1192) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:34:03.948+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:34:03.949+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:34:03.949+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:34:03.955+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:34:03.953+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:34:03.955+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:34:03.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.023 seconds
[2024-09-10T17:34:34.329+0000] {processor.py:186} INFO - Started process (PID=1255) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:34:34.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:34:34.332+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:34:34.331+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:34:34.339+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:34:34.337+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:34:34.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:34:34.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.027 seconds
[2024-09-10T17:35:04.941+0000] {processor.py:186} INFO - Started process (PID=1318) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:35:04.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:35:04.944+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:35:04.943+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:35:04.949+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:35:04.947+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:35:04.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:35:04.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.023 seconds
[2024-09-10T17:35:35.138+0000] {processor.py:186} INFO - Started process (PID=1381) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:35:35.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:35:35.139+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:35:35.139+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:35:35.145+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:35:35.144+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:35:35.145+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:35:35.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.026 seconds
[2024-09-10T17:36:05.417+0000] {processor.py:186} INFO - Started process (PID=1445) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:36:05.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:36:05.419+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:36:05.419+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:36:05.427+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:36:05.425+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:36:05.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:36:05.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.026 seconds
[2024-09-10T17:36:35.694+0000] {processor.py:186} INFO - Started process (PID=1508) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:36:35.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:36:35.700+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:36:35.700+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:36:35.709+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:36:35.707+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:36:35.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:36:35.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.043 seconds
[2024-09-10T17:37:06.029+0000] {processor.py:186} INFO - Started process (PID=1571) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T17:37:06.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T17:37:06.031+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:37:06.031+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T17:37:06.037+0000] {logging_mixin.py:190} INFO - [2024-09-10T17:37:06.036+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 51, in <module>
    training_model_tasks >> choose_best_model >> [is_accurate, is_inaccurate]
                                                  ^^^^^^^^^^^
NameError: name 'is_accurate' is not defined. Did you mean: 'inaccurate'?
[2024-09-10T17:37:06.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T17:37:06.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.024 seconds
[2024-09-10T18:22:16.241+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:22:16.242+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:22:16.243+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:16.243+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:22:16.262+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:22:16.403+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:16.403+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:simple_dag_example
[2024-09-10T18:22:16.409+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:16.408+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:simple_dag_example
[2024-09-10T18:22:16.414+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:16.414+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:simple_dag_example
[2024-09-10T18:22:16.419+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:16.419+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:simple_dag_example
[2024-09-10T18:22:16.422+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:16.422+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:simple_dag_example
[2024-09-10T18:22:16.425+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:16.425+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:simple_dag_example
[2024-09-10T18:22:16.428+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:16.428+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:simple_dag_example
[2024-09-10T18:22:16.428+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:16.428+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:22:16.435+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:16.435+0000] {dag.py:3252} INFO - Creating ORM DAG for simple_dag_example
[2024-09-10T18:22:16.441+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:16.440+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:22:16.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.211 seconds
[2024-09-10T18:22:46.483+0000] {processor.py:186} INFO - Started process (PID=58) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:22:46.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:22:46.485+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:46.485+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:22:46.495+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:22:46.520+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:46.519+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:22:46.539+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:22:46.539+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:22:46.552+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.074 seconds
[2024-09-10T18:23:16.771+0000] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:23:16.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:23:16.775+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:23:16.774+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:23:16.784+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:23:16.802+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:23:16.801+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:23:16.825+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:23:16.824+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:23:16.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.079 seconds
[2024-09-10T18:23:47.055+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:23:47.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:23:47.057+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:23:47.057+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:23:47.067+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:23:47.096+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:23:47.095+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:23:47.118+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:23:47.118+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:23:47.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.083 seconds
[2024-09-10T18:24:17.289+0000] {processor.py:186} INFO - Started process (PID=79) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:24:17.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:24:17.295+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:24:17.294+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:24:17.306+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:24:17.320+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:24:17.320+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:24:17.333+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:24:17.333+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:24:17.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.060 seconds
[2024-09-10T18:24:47.568+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:24:47.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:24:47.570+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:24:47.569+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:24:47.577+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:24:47.592+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:24:47.592+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:24:47.606+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:24:47.605+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:24:47.614+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.052 seconds
[2024-09-10T18:25:17.828+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:25:17.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:25:17.831+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:25:17.831+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:25:17.846+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:25:17.865+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:25:17.865+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:25:17.878+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:25:17.878+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:25:17.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.063 seconds
[2024-09-10T18:25:48.106+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:25:48.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:25:48.108+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:25:48.108+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:25:48.120+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:25:48.138+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:25:48.138+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:25:48.158+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:25:48.158+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:25:48.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.076 seconds
[2024-09-10T18:26:18.396+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:26:18.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:26:18.399+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:26:18.398+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:26:18.409+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:26:18.430+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:26:18.430+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:26:18.476+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:26:18.475+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:26:18.486+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.095 seconds
[2024-09-10T18:26:48.664+0000] {processor.py:186} INFO - Started process (PID=114) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:26:48.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:26:48.666+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:26:48.666+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:26:48.676+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:26:48.696+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:26:48.696+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:26:48.728+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:26:48.727+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:26:48.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.175 seconds
[2024-09-10T18:27:19.004+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:27:19.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:27:19.008+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:27:19.008+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:27:19.024+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:27:19.050+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:27:19.050+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:27:19.160+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:27:19.160+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:27:19.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.174 seconds
[2024-09-10T18:27:49.352+0000] {processor.py:186} INFO - Started process (PID=128) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:27:49.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:27:49.355+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:27:49.355+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:27:49.365+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:27:49.391+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:27:49.391+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:27:49.413+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:27:49.413+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:27:49.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.080 seconds
[2024-09-10T18:28:19.713+0000] {processor.py:186} INFO - Started process (PID=135) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:28:19.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:28:19.715+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:28:19.715+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:28:19.726+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:28:19.751+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:28:19.750+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:28:19.788+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:28:19.787+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:28:19.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.107 seconds
[2024-09-10T18:28:49.988+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:28:49.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:28:49.993+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:28:49.992+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:28:50.003+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:28:50.017+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:28:50.016+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:28:50.029+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:28:50.028+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:28:50.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.063 seconds
[2024-09-10T18:29:20.201+0000] {processor.py:186} INFO - Started process (PID=149) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:29:20.206+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:29:20.210+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:29:20.210+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:29:20.222+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:29:20.237+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:29:20.237+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:29:20.250+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:29:20.250+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:29:20.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.145 seconds
[2024-09-10T18:29:50.530+0000] {processor.py:186} INFO - Started process (PID=156) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:29:50.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:29:50.535+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:29:50.534+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:29:50.544+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:29:50.572+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:29:50.571+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:29:50.685+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:29:50.685+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:29:50.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.176 seconds
[2024-09-10T18:30:20.842+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:30:20.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:30:20.844+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:30:20.844+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:30:20.853+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:30:20.876+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:30:20.875+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:30:20.973+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:30:20.972+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:30:20.986+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.149 seconds
[2024-09-10T18:30:51.200+0000] {processor.py:186} INFO - Started process (PID=170) to work on /opt/airflow/dags/my_dag.py
[2024-09-10T18:30:51.201+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-09-10T18:30:51.203+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:30:51.203+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-09-10T18:30:51.212+0000] {processor.py:925} INFO - DAG(s) 'simple_dag_example' retrieved from /opt/airflow/dags/my_dag.py
[2024-09-10T18:30:51.227+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:30:51.227+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-10T18:30:51.240+0000] {logging_mixin.py:190} INFO - [2024-09-10T18:30:51.240+0000] {dag.py:4156} INFO - Setting next_dagrun for simple_dag_example to 2023-09-10 00:00:00+00:00, run_after=2023-09-11 00:00:00+00:00
[2024-09-10T18:30:51.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_dag.py took 0.060 seconds
